version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      root-development-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: /hosted
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /hosted
    schedule:
      interval: weekly
