name: Official SDK Compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "11 5 * * 1"

permissions:
  contents: read

jobs:
  locked-sdks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |-
            package-lock.json
            compat/sdk/package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npm ci
        working-directory: compat/sdk
      - run: npm test
        working-directory: compat/sdk
